# Generated by Django 2.2.1 on 2019-06-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='csv_model',
            fields=[
                ('trans_account', models.IntegerField()),
                ('trans_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('trans_date', models.DateField()),
                ('trans_posted_date', models.DateField()),
                ('trans_cheque', models.CharField(max_length=20)),
                ('trans_desc', models.CharField(max_length=100)),
                ('cr_or_dr', models.CharField(max_length=2)),
                ('value', models.FloatField()),
                ('balance', models.FloatField()),
                ('transc_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
