# Generated by Django 2.2.1 on 2019-06-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='csv_fm_txn',
            fields=[
                ('txnID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('accID', models.IntegerField(default=0)),
                ('txnDate', models.DateField()),
                ('txnPostedDate', models.DateField()),
                ('txnCheque', models.IntegerField()),
                ('txnDir', models.CharField(max_length=1)),
                ('txnDesc', models.CharField(max_length=100)),
                ('txnValue', models.FloatField()),
                ('txnBalance', models.FloatField()),
                ('transc_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
