# Generated by Django 2.2 on 2019-06-20 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='fm_txn',
            fields=[
                ('txnID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('accID', models.IntegerField(default=0)),
                ('txnDate', models.DateField()),
                ('txnPostedDate', models.DateField()),
                ('txnCheque', models.IntegerField()),
                ('txnDir', models.CharField(max_length=1)),
                ('txnDesc', models.CharField(max_length=100)),
                ('txnValue', models.FloatField()),
                ('txnBalance', models.FloatField()),
                ('txnAuditFile', models.URLField()),
                ('txnType', models.CharField(default='U', max_length=1)),
                ('txnAccounted', models.BooleanField(default=0)),
                ('txnAudited', models.BooleanField(default=0)),
                ('prID', models.IntegerField(null=True)),
                ('ptcID', models.IntegerField(null=True)),
                ('bhlID', models.IntegerField(null=True)),
                ('transc_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='fm_utrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utanDate', models.DateField(auto_now_add=True)),
                ('utranID', models.IntegerField(null=True)),
                ('txnID', models.IntegerField(null=True)),
                ('utranDesc', models.CharField(max_length=50, verbose_name='Description')),
                ('utranValue', models.IntegerField(null=True, verbose_name='Amount')),
                ('utranConfirmed', models.CharField(default='N', max_length=1)),
                ('utranSender', models.CharField(default='no', max_length=10)),
                ('utranReceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Receiver')),
            ],
        ),
        migrations.CreateModel(
            name='fm_user_extend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uopeningBalance', models.IntegerField(default=0)),
                ('uBalance', models.IntegerField(default=0)),
                ('uUnconfirmed', models.IntegerField(default=0)),
                ('uDeclined', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='fm_project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prTitle', models.CharField(max_length=50)),
                ('prDesc', models.CharField(max_length=200)),
                ('prBudget', models.IntegerField(default=0)),
                ('prBalance', models.IntegerField(default=0)),
                ('prManagers_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_project_manager', to=settings.AUTH_USER_MODEL)),
                ('prManagers_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_project_manager', to=settings.AUTH_USER_MODEL)),
                ('prManagers_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_project_manager', to=settings.AUTH_USER_MODEL)),
                ('prManagers_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fourth_project_manager', to=settings.AUTH_USER_MODEL)),
                ('prManagers_5', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fifth_project_manager', to=settings.AUTH_USER_MODEL)),
                ('prManagers_6', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sixth_project_manager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
