# Generated by Django 2.2 on 2019-06-20 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fm_budgethead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpAPP.fm_project')),
            ],
        ),
    ]
