# Generated by Django 2.2.1 on 2019-06-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvmodel',
            name='balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='csvmodel',
            name='value',
            field=models.FloatField(),
        ),
    ]
