# Generated by Django 2.2.1 on 2019-06-07 01:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv_fm_txn',
            name='txnAuditFile',
            field=models.FileField(default=django.utils.timezone.now, upload_to='file_link'),
            preserve_default=False,
        ),
    ]
