# Generated by Django 2.2 on 2019-06-20 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0002_fm_budgethead'),
    ]

    operations = [
        migrations.AddField(
            model_name='fm_budgethead',
            name='bhBalance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fm_budgethead',
            name='bhBalanceDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='fm_budgethead',
            name='bhLimit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fm_budgethead',
            name='bhTitle',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
