# Generated by Django 2.2.1 on 2019-06-07 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0002_csv_fm_txn_txnauditfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_fm_txn',
            name='txnAuditFile',
            field=models.CharField(max_length=200),
        ),
    ]
