# Generated by Django 2.2.1 on 2019-06-07 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0003_auto_20190607_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_fm_txn',
            name='txnAuditFile',
            field=models.URLField(),
        ),
    ]
