# Generated by Django 2.2.1 on 2019-06-04 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0003_csv_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CSVmodel',
            new_name='csv_models',
        ),
        migrations.DeleteModel(
            name='CSV_table',
        ),
    ]
