# Generated by Django 2.2 on 2019-06-22 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0003_auto_20190620_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm_project',
            name='prBalance',
            field=models.IntegerField(default=0, verbose_name='Balance of budget'),
        ),
        migrations.AlterField(
            model_name='fm_project',
            name='prBudget',
            field=models.IntegerField(default=0, verbose_name='Total Budget'),
        ),
        migrations.AlterField(
            model_name='fm_project',
            name='prDesc',
            field=models.CharField(max_length=200, verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='fm_project',
            name='prManagers_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_project_manager', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager 1'),
        ),
        migrations.AlterField(
            model_name='fm_project',
            name='prManagers_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_project_manager', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager 2'),
        ),
        migrations.AlterField(
            model_name='fm_project',
            name='prManagers_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='third_project_manager', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager 3'),
        ),
        migrations.AlterField(
            model_name='fm_project',
            name='prManagers_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fourth_project_manager', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager 4'),
        ),
        migrations.AlterField(
            model_name='fm_project',
            name='prManagers_5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fifth_project_manager', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager 5'),
        ),
        migrations.AlterField(
            model_name='fm_project',
            name='prManagers_6',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sixth_project_manager', to=settings.AUTH_USER_MODEL, verbose_name='Project Manager 6'),
        ),
        migrations.AlterField(
            model_name='fm_project',
            name='prTitle',
            field=models.CharField(max_length=50, verbose_name='Project Title'),
        ),
    ]
