# Generated by Django 2.2 on 2019-06-22 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0004_auto_20190622_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm_budgethead',
            name='bhTitle',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
