# Generated by Django 2.2.1 on 2019-06-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0004_auto_20190604_0934'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='csv_models',
            new_name='csv_model',
        ),
    ]
