# Generated by Django 2.2 on 2019-06-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0005_auto_20190622_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm_budgethead',
            name='bhTitle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
