# Generated by Django 2.2.1 on 2019-06-07 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0006_auto_20190607_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='csv_fm_txn',
            name='bhlID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='csv_fm_txn',
            name='prID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='csv_fm_txn',
            name='ptcID',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='csv_fm_txn',
            name='txnAccounted',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='csv_fm_txn',
            name='txnAudited',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='csv_fm_txn',
            name='txnType',
            field=models.CharField(default='U', max_length=1),
        ),
    ]
