# Generated by Django 2.2.1 on 2019-06-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0007_auto_20190607_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfilestorage',
            name='txnAuditFileStorage',
            field=models.FileField(unique=True, upload_to='file_link'),
        ),
    ]
