# Generated by Django 2.2 on 2019-06-24 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erpAPP', '0008_fm_ptcform'),
    ]

    operations = [
        migrations.CreateModel(
            name='fm_ptctrans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptctransDate', models.DateField()),
                ('ptctransValue', models.IntegerField()),
                ('ptctransInvoiceStatus', models.CharField(max_length=1)),
                ('ptctransInvoiceFile', models.FileField(unique=True, upload_to='InvoiceFile')),
                ('ptctransApproved', models.BooleanField(default=0)),
                ('ptctransApprovedBy', models.CharField(max_length=50, null=True)),
                ('ptcVendor', models.CharField(max_length=50)),
                ('ptcDesc', models.CharField(max_length=200)),
                ('prID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpAPP.fm_project')),
                ('ptcID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpAPP.fm_ptcform')),
                ('ptctransHead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpAPP.fm_budgethead')),
                ('uID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
