# Generated by Django 2.2.1 on 2019-06-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0008_auto_20190607_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVfileStorage',
        ),
    ]
