# Generated by Django 2.2 on 2019-06-25 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0009_fm_ptctrans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm_ptcform',
            name='prID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpAPP.fm_project', verbose_name='Select Project'),
        ),
    ]
