# Generated by Django 2.2.1 on 2019-06-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0010_auto_20190609_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_fm_txn',
            name='txnAuditFile',
            field=models.URLField(),
        ),
    ]
