# Generated by Django 2.2 on 2019-06-25 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0010_auto_20190625_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm_ptcform',
            name='prID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='erpAPP.fm_project'),
        ),
    ]
