# Generated by Django 2.2.1 on 2019-06-09 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0011_auto_20190609_1036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='csv_fm_txn',
            new_name='fm_txn',
        ),
    ]
