# Generated by Django 2.2 on 2019-06-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0011_auto_20190625_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm_ptcform',
            name='ptcType',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='fm_ptcform',
            name='ptcValue',
            field=models.IntegerField(default=0),
        ),
    ]
