# Generated by Django 2.2 on 2019-06-11 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erpAPP', '0012_auto_20190609_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='fm_utrans_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utranID', models.IntegerField(null=True)),
                ('txnID', models.IntegerField(null=True)),
                ('utranDesc', models.CharField(max_length=50, verbose_name='Description')),
                ('utranValue', models.IntegerField(verbose_name='Amount')),
                ('utranConfirmed', models.CharField(max_length=1)),
                ('utranSender', models.CharField(default='no', max_length=10)),
                ('utranReceiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Receiver')),
            ],
        ),
    ]
