# Generated by Django 2.2 on 2019-06-26 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0012_auto_20190625_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fm_ptcform',
            options={'get_latest_by': 'uID'},
        ),
    ]
