# Generated by Django 2.2 on 2019-06-11 06:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erpAPP', '0013_fm_utrans_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fm_utrans_table',
            new_name='fm_utrans',
        ),
    ]
