# Generated by Django 2.2 on 2019-06-11 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0014_auto_20190611_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm_utrans',
            name='utranValue',
            field=models.IntegerField(null=True, verbose_name='Amount'),
        ),
    ]
