# Generated by Django 2.2 on 2019-06-30 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0014_fm_ptcform_txnid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fm_utrans',
            name='utranID',
        ),
    ]
