# Generated by Django 2.2 on 2019-06-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0015_remove_fm_utrans_utranid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fm_utrans',
            old_name='utanDate',
            new_name='utranDate',
        ),
    ]
