# Generated by Django 2.2 on 2019-06-17 06:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0016_auto_20190617_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='fm_utrans',
            name='utanDate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
