# Generated by Django 2.2 on 2019-07-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0016_auto_20190630_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm_utrans',
            name='txnID',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
