# Generated by Django 2.2 on 2019-06-18 08:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erpAPP', '0017_fm_utrans_utandate'),
    ]

    operations = [
        migrations.CreateModel(
            name='fm_user_extend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uopeningBalance', models.IntegerField(default=0)),
                ('uBalance', models.IntegerField(default=0)),
                ('uUnconfirmed', models.IntegerField(default=0)),
                ('uDeclined', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
