# Generated by Django 2.2 on 2019-06-18 07:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erpAPP', '0018_fm_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='fm_user',
            new_name='fm_user_extend',
        ),
    ]
