# Generated by Django 2.2 on 2019-07-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0018_auto_20190708_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm_txn',
            name='txnDir',
            field=models.CharField(max_length=2),
        ),
    ]
