# Generated by Django 2.2 on 2019-07-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0019_auto_20190709_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm_user_extend',
            name='uBalance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fm_user_extend',
            name='uDeclined',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fm_user_extend',
            name='uUnconfirmed',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fm_user_extend',
            name='uopeningBalance',
            field=models.FloatField(default=0),
        ),
    ]
