# Generated by Django 2.2 on 2019-07-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0020_auto_20190711_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm_txn',
            name='accID',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fm_txn',
            name='bhlID',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fm_txn',
            name='prID',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fm_txn',
            name='ptcID',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='fm_txn',
            name='txnCheque',
            field=models.FloatField(),
        ),
    ]
