# Generated by Django 2.2 on 2019-07-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0021_auto_20190711_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm_project',
            name='prBalance',
            field=models.FloatField(default=0, verbose_name='Balance of budget'),
        ),
        migrations.AlterField(
            model_name='fm_project',
            name='prBudget',
            field=models.FloatField(default=0, verbose_name='Total Budget'),
        ),
        migrations.AlterField(
            model_name='fm_utrans',
            name='utranValue',
            field=models.FloatField(null=True, verbose_name='Amount'),
        ),
    ]
