# Generated by Django 2.2 on 2019-07-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0022_auto_20190711_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm_budgethead',
            name='bhBalance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fm_budgethead',
            name='bhLimit',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fm_ptcform',
            name='ptcValue',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='fm_ptctrans',
            name='ptctransValue',
            field=models.FloatField(),
        ),
    ]
