# Generated by Django 2.2 on 2019-07-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erpAPP', '0023_auto_20190711_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fm_txn',
            name='accID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fm_txn',
            name='bhlID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fm_txn',
            name='prID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fm_txn',
            name='ptcID',
            field=models.IntegerField(null=True),
        ),
    ]
